name: Accordion
main: at.yawk.accordion.minecraft.example.AccordionBukkit
version: 1.0
description: Accordion example plugin for bukkit
commands:
   ping:
      description: Broadcast a ping packet (results can be seen in the log)
      usage: /ping <number>
