name: AccordionExample
main: at.yawk.accordion.minecraft.example.AccordionBukkitExample
version: 1.0
description: Accordion example plugin for bukkit
depends: [Accordion]
commands:
   ping:
      description: Broadcast a ping packet (results can be seen in the log)
      usage: /ping <number>
